import * as THREE from 'three';
import {GLTFLoader} from './vendor/three/examples/jsm/loaders/GLTFLoader.js';
import {clone} from './vendor/three/examples/jsm/utils/SkeletonUtils.js';
import {mergeGeometries} from './vendor/three/examples/jsm/utils/BufferGeometryUtils.js';
import {RoomEnvironment} from './vendor/three/examples/jsm/environments/RoomEnvironment.js';
import {advanceYaw} from './r10-character.js';
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z);let sourcePromise;
function closeLoop(clip){const duration=clip.duration,steps=Math.ceil(duration*60);clip.tracks=clip.tracks.map(track=>{const sample=track.createInterpolant(),size=track.getValueSize(),first=Array.from(sample.evaluate(0)),times=[],values=[];for(let i=0;i<=steps;i++){const t=duration*i/steps,v=Array.from(sample.evaluate(t)),u=THREE.MathUtils.clamp((t-duration+.18)/.18,0,1),blend=u*u*(3-2*u);times.push(t);if(size===4){const q=new THREE.Quaternion(...v).normalize().slerp(new THREE.Quaternion(...first).normalize(),blend);values.push(...q.toArray());}else values.push(...v.map((x,k)=>x+(first[k]-x)*blend));}return new track.constructor(track.name,times,values);});}
export function loadDragon(){return sourcePromise??=(async()=>{
 const g=await new GLTFLoader().loadAsync(new URL('./assets/r10-boss/dragon-base.glb',import.meta.url).href);
 g.blackTexture=await new THREE.TextureLoader().loadAsync(new URL('./assets/r10-boss/dragon_black.png',import.meta.url).href);g.blackTexture.colorSpace=THREE.SRGBColorSpace;g.blackTexture.anisotropy=8;
 const rootTrack=g.animations.find(c=>c.name==='idle').tracks.find(t=>t.name==='base.position'),base=rootTrack?Array.from(rootTrack.values.slice(0,3)):null;
 for(const c of g.animations)for(const t of c.tracks)if(t.name==='base.position'&&base)for(let i=0;i<t.values.length;i+=3){t.values[i]=base[0];t.values[i+1]=base[1];}
 closeLoop(g.animations.find(c=>c.name==='walk'));
 return g;
})();}
function solid(geo,mat,parent,pos,scale){const m=new THREE.Mesh(geo,mat);if(pos)m.position.fromArray(pos);if(scale)m.scale.fromArray(scale);parent.add(m);m.castShadow=m.receiveShadow=true;return m;}
function horn(parent,points,r,mat){const curve=new THREE.CatmullRomCurve3(points.map(p=>V(...p))),n=24,k=9,p=[],idx=[],frames=curve.computeFrenetFrames(n,false);for(let i=0;i<=n;i++){const at=curve.getPoint(i/n),radius=r*Math.pow(1-i/n,.82)*(1+(r>.014?.055:0)*Math.sin(i/n*Math.PI*34)*(1-i/n))+.00025;for(let j=0;j<k;j++){const q=at.clone().addScaledVector(frames.normals[i],Math.cos(j/k*Math.PI*2)*radius).addScaledVector(frames.binormals[i],Math.sin(j/k*Math.PI*2)*radius);p.push(...q.toArray());if(i<n){const a=i*k+j,b=i*k+(j+1)%k;idx.push(a,b,a+k,b,b+k,a+k);}}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));geo.setIndex(idx);geo.computeVertexNormals();return solid(geo,mat,parent);}
function skinGeometry(positions,indices,skinIndices,weights,uv){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(skinIndices,4));g.setAttribute('skinWeight',new THREE.Float32BufferAttribute(weights,4));if(uv)g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g;}
function muzzle(parent,mat,rings){const p=[],ix=[],n=8;for(const [z,y,w,h]of rings)for(let j=0;j<n;j++){const a=(j+.5)/n*Math.PI*2;p.push(Math.cos(a)*w,y+Math.sin(a)*h,z);}for(let r=0;r<rings.length-1;r++)for(let j=0;j<n;j++){const a=r*n+j,b=r*n+(j+1)%n;ix.push(a,b,a+n,b,b+n,a+n);}for(let j=1;j<n-1;j++){ix.push(0,j+1,j);const a=(rings.length-1)*n;ix.push(a,a+j,a+j+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setIndex(ix);g.computeVertexNormals();return solid(g,mat,parent);}
function armorLeaf(parent,mat,at,w,l,h,rotation=[0,0,0]){const outline=[[0,1.25],[-.72,.42],[-1,-.45],[-.38,-.84],[.52,-.77],[.90,-.31],[.58,.48]],P=[],I=[],n=outline.length;for(const [scale,y]of [[1,0],[.84,h]])for(const [x,z]of outline)P.push(x*w*scale,y,z*l*scale);P.push(0,h*1.55,-l*.12);for(let j=0;j<n;j++){const k=(j+1)%n;I.push(j,k,j+n,k,k+n,j+n,n*2,j+n,k+n);}for(let j=1;j<n-1;j++)I.push(0,j+1,j);for(let k=0;k<I.length;k+=3)[I[k+1],I[k+2]]=[I[k+2],I[k+1]];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(P,3));g.setIndex(I);g.computeVertexNormals();const m=solid(g,mat,parent,at);m.rotation.set(...rotation);return m;}
function membraneTexture(){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d'),im=x.createImageData(1024,1024);let s=93;for(let i=0;i<im.data.length;i+=4){s=(s*1664525+1013904223)>>>0;const noise=(s/4294967296-.5)*12;im.data[i]=110+noise;im.data[i+1]=43+noise*.4;im.data[i+2]=38+noise*.4;im.data[i+3]=255;}x.putImageData(im,0,0);x.strokeStyle='#482421';x.lineWidth=1.3;for(let k=0;k<4;k++)for(let j=1;j<20;j++){const at=k*256+j*12;x.beginPath();x.moveTo(k*256+128,1024);x.bezierCurveTo(at,760,at+Math.sin(j)*28,400,at,0);x.stroke();}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function groundConstrainedWing(mesh){mesh.material=mesh.material.clone();mesh.material.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <skinning_vertex>','#include <skinning_vertex>\ntransformed.y=max(transformed.y,0.012);');};mesh.material.customProgramCacheKey=()=> 'dragon-wing-ground-v1';const original=mesh.getVertexPosition;mesh.getVertexPosition=function(index,target){original.call(this,index,target);target.y=Math.max(target.y,.012);return target;};}
function batch(group){group.updateWorldMatrix(true,true);const inv=group.matrixWorld.clone().invert(),parts=new Map(),remove=[];group.traverse(o=>{if(!o.isMesh||o.isSkinnedMesh)return;const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();for(const key of Object.keys(g.attributes))if(!['position','normal','uv'].includes(key))g.deleteAttribute(key);if(!g.attributes.uv)g.setAttribute('uv',new THREE.Float32BufferAttribute(new Float32Array(g.attributes.position.count*2),2));g.applyMatrix4(inv.clone().multiply(o.matrixWorld));if(!parts.has(o.material))parts.set(o.material,[]);parts.get(o.material).push(g);remove.push(o)});remove.forEach(o=>o.removeFromParent());for(const [mat,geos]of parts){solid(mergeGeometries(geos,false),mat,group);geos.forEach(g=>g.dispose())}}
export class R10Dragon{
 constructor(gltf,{detail='high'}={}){
  this.detail=detail;
  this.root=new THREE.Group();this.body=clone(gltf.scene);this.root.add(this.body);this.bones={};this.body.traverse(o=>{if(o.isBone)this.bones[o.name]=o;if(o.isSkinnedMesh)this.skin=o;});
  this.materials={hide:new THREE.MeshStandardMaterial({color:0x3c1010,roughness:.82,metalness:.15,side:THREE.DoubleSide}),scale:new THREE.MeshStandardMaterial({color:0x34343c,roughness:.48,metalness:.38}),ridge:new THREE.MeshStandardMaterial({color:0x222530,roughness:.44,metalness:.45}),horn:new THREE.MeshStandardMaterial({color:0x484149,roughness:.5,metalness:.3}),tooth:new THREE.MeshStandardMaterial({color:0x746657,roughness:.57,metalness:.12}),mouth:new THREE.MeshStandardMaterial({color:0x100103,roughness:.96}),eye:new THREE.MeshStandardMaterial({color:0xec2910,emissive:0xff2805,emissiveIntensity:1.5,roughness:.2}),membrane:new THREE.MeshStandardMaterial({color:0x50100f,roughness:.86,metalness:.04,side:THREE.DoubleSide})};
  this.materials.hide.color.setHex(0x160b0c);this.materials.hide.roughness=.61;this.materials.hide.emissive.setHex(0x791208);this.materials.hide.emissiveIntensity=.035;this.materials.scale.color.setHex(0x25242b);this.materials.scale.roughness=.53;this.materials.scale.metalness=.42;this.materials.ridge.color.setHex(0x29242a);this.materials.horn.color.setHex(0x322a2c);this.materials.membrane.color.setHex(0x9b726c);this.materials.membrane.map=membraneTexture();
  this.materials.plate=this.materials.scale.clone();this.materials.plate.map=gltf.blackTexture;this.materials.plate.bumpMap=gltf.blackTexture;this.materials.plate.bumpScale=.0017;this.materials.plate.color.setHex(0x6e4b4d);this.materials.plate.roughness=.57;this.materials.plate.metalness=.30;
  this.materials.head=this.materials.plate.clone();this.materials.head.color.setHex(0x706267);this.materials.head.bumpScale=.0027;
  this.skin.material=this.materials.hide;this.skin.frustumCulled=false;this.createScales();
  this.mixer=new THREE.AnimationMixer(this.body);this.clips=Object.fromEntries(gltf.animations.map(c=>[c.name,c]));this.actions=Object.fromEntries(gltf.animations.map(c=>[c.name,this.mixer.clipAction(c)]));this.current='idle';this.actions.idle.play();this.actions.idle.time=.3;this.mixer.update(0);this.root.updateMatrixWorld(true);
  this.buildHead();this.buildClaws();this.buildDorsal();this.buildArmor();this.buildWings();for(const bone of Object.values(this.bones))for(const group of [...bone.children])if(group.isGroup)batch(group);
  this.t=0;this.lastT=null;this.yaw=null;this.lastHurt=0;this.hurtUntil=0;this.effects=true;this.overlayRestore=[];this.state='idle';this.footLocks={};this.lastFootLocal={};this.ground();
 }
 createScales(){
  // Bevelled, overlapping mineral scales deform with the original 32-bone skin.
  // Small six-sided shields replace the former large triangular throat panels.
  const g=this.skin.geometry,p=g.attributes.position,n=g.attributes.normal,si=g.attributes.skinIndex,sw=g.attributes.skinWeight,ix=g.index?.array||Array.from({length:p.count},(_,i)=>i);
  const pos=[],indices=[],joints=[],weights=[],colors=[],outNormals=[],kept=[],groups=[];let count=0,seed=7103;
  const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
  this.root.updateWorldMatrix(true,true);const normalMatrix=new THREE.Matrix3().getNormalMatrix(this.skin.matrixWorld);
  for(let i=0;i<ix.length;i+=3){
   const ids=[ix[i],ix[i+1],ix[i+2]],verts=ids.map(j=>V().fromBufferAttribute(p,j)),norms=ids.map(j=>V().fromBufferAttribute(n,j));
   let wing=0,throat=0,torso=0;for(const id of ids)for(let k=0;k<4;k++){const name=this.skin.skeleton.bones[si.getComponent(id,k)].name,w=sw.getComponent(id,k);if(name.startsWith('wing'))wing+=w;if(name.startsWith('neck'))throat+=w;if(name==='back1')torso+=w;}
   if(wing>1.5)continue;
   const norm=norms.reduce((s,v)=>s.add(v),V()).normalize().applyMatrix3(normalMatrix).normalize(),center=verts.reduce((s,v)=>s.add(v),V()).multiplyScalar(1/3).applyMatrix4(this.skin.matrixWorld);
   const hot=(throat>1.2&&norm.z>.24)||(torso>1.2&&norm.y<-.12&&center.z>-.12);
   groups.push({start:kept.length,count:3,materialIndex:hot?1:0});kept.push(...ids);
   const area=verts[1].clone().sub(verts[0]).cross(verts[2].clone().sub(verts[0])).length()/2,steps=Math.max(1,Math.min(12,Math.ceil(Math.sqrt(area/(this.detail==='high'?.00028:this.detail==='balanced'?.00065:.0012)))));
   const add=(bary,height,color)=>{const point=V(),normal=V(),influence=new Map();for(let j=0;j<3;j++){point.addScaledVector(verts[j],bary[j]);normal.addScaledVector(norms[j],bary[j]);for(let k=0;k<4;k++){const bone=si.getComponent(ids[j],k);influence.set(bone,(influence.get(bone)||0)+sw.getComponent(ids[j],k)*bary[j]);}}point.addScaledVector(normal.normalize(),height);pos.push(...point.toArray());outNormals.push(...normal.toArray());colors.push(...color);const sorted=[...influence].sort((a,b)=>b[1]-a[1]).slice(0,4),sum=sorted.reduce((v,x)=>v+x[1],0),J=sorted.map(x=>x[0]),W=sorted.map(x=>x[1]/sum);while(J.length<4){J.push(0);W.push(0)}joints.push(...J);weights.push(...W);};
   const bary=(u,v)=>[1-u-v,u,v];
   const shield=tri=>{const center=tri[0].map((_,j)=>(tri[0][j]+tri[1][j]+tri[2][j])/3),outline=[];
    for(let j=0;j<3;j++)for(const mix of [.17,.83])outline.push(tri[j].map((v,k)=>v+(tri[(j+1)%3][k]-v)*mix));
    const off=pos.length/3,height=.0017+Math.sqrt(area)/steps*(.055+random()*.035),tone=.19+random()*.15,col=[tone*.86,tone*.91,tone];
    for(const [scale,h]of [[hot?.93:1.02,.0003],[.78,height]])for(const v of outline)add(v.map((x,j)=>center[j]+(x-center[j])*scale),h,col);
    add(center,height*1.35,col.map(x=>x*1.12));
    for(let j=0;j<6;j++){const k=(j+1)%6;indices.push(off+j,off+k,off+j+6,off+k,off+k+6,off+j+6,off+12,off+j+6,off+k+6);}count++;
   };
   for(let u=0;u<steps;u++)for(let v=0;v<steps-u;v++){shield([bary(u/steps,v/steps),bary((u+1)/steps,v/steps),bary(u/steps,(v+1)/steps)]);if(v<steps-u-1)shield([bary((u+1)/steps,v/steps),bary((u+1)/steps,(v+1)/steps),bary(u/steps,(v+1)/steps)]);}
  }
  this.skin.geometry=g.clone();const cold=groups.filter(g=>g.materialIndex===0).flatMap(g=>kept.slice(g.start,g.start+3)),hot=groups.filter(g=>g.materialIndex===1).flatMap(g=>kept.slice(g.start,g.start+3));this.skin.geometry.setIndex([...cold,...hot]);this.skin.geometry.clearGroups();this.skin.geometry.addGroup(0,cold.length,0);this.skin.geometry.addGroup(cold.length,hot.length,1);
  this.fissureMaterial=new THREE.MeshStandardMaterial({color:0x180504,emissive:0xff2904,emissiveIntensity:2.1,roughness:.72,side:THREE.DoubleSide});
  this.fissureMaterial.onBeforeCompile=shader=>{
   shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vFaultPosition;').replace('#include <begin_vertex>','#include <begin_vertex>\nvFaultPosition=position;');
   shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vFaultPosition;').replace('#include <emissivemap_fragment>',`#include <emissivemap_fragment>
    vec3 fp=vFaultPosition;
    float faultA=abs(sin(fp.x*63.0+sin(fp.y*39.0)*1.9+sin(fp.z*53.0)*0.7));
    float faultB=abs(sin(fp.z*74.0+sin(fp.x*55.0)*1.4+sin(fp.y*71.0)*0.6));
    float fracture=max(1.0-smoothstep(0.025,0.32,faultA),0.55*(1.0-smoothstep(0.01,0.10,faultB)));
    totalEmissiveRadiance*=fracture;
   `);
  };this.fissureMaterial.customProgramCacheKey=()=> 'obsidian-faults-v3';
  this.skin.material=[this.materials.hide,this.fissureMaterial];
  const plates=skinGeometry(pos,indices,joints,weights);plates.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const N=plates.attributes.normal;for(let j=0;j<N.count;j++){const n=V().fromBufferAttribute(N,j).lerp(V(...outNormals.slice(j*3,j*3+3)),.65).normalize();N.setXYZ(j,n.x,n.y,n.z);}
  const mat=new THREE.MeshStandardMaterial({color:0x302c30,vertexColors:true,roughness:.60,metalness:.31});
  this.scaleMesh=new THREE.SkinnedMesh(plates,mat);this.scaleMesh.frustumCulled=false;this.skin.parent.add(this.scaleMesh);this.scaleMesh.bind(this.skin.skeleton,this.skin.bindMatrix);this.scaleCount=count;
 }
 mountWorld(group,bone){this.root.add(group);this.root.updateMatrixWorld(true);this.bones[bone].attach(group);return group;}
 projectTexture(mesh,region){const source=this.skin.geometry,ix=source.index.array,si=source.attributes.skinIndex,sw=source.attributes.skinWeight,uv=source.attributes.uv,triangles=[];this.skin.skeleton.update();for(let k=0;k<ix.length;k+=3){const ids=[ix[k],ix[k+1],ix[k+2]];let weight=0;for(const id of ids)for(let n=0;n<4;n++)if(this.skin.skeleton.bones[si.getComponent(id,n)].name===region)weight+=sw.getComponent(id,n);if(weight<1.2)continue;triangles.push({ids,triangle:new THREE.Triangle(...ids.map(i=>this.skin.getVertexPosition(i,V()).applyMatrix4(this.skin.matrixWorld)))});}const a=mesh.geometry.attributes.position,result=[];for(let i=0;i<a.count;i++){const point=V().fromBufferAttribute(a,i),closest=V();let best=null,dist=Infinity;for(const data of triangles){data.triangle.closestPointToPoint(point,closest);const d=closest.distanceToSquared(point);if(d<dist){dist=d;best={ids:data.ids,bary:data.triangle.getBarycoord(closest,V())};}}let u=0,v=0;if(best)for(let j=0;j<3;j++){u+=uv.getX(best.ids[j])*best.bary.getComponent(j);v+=uv.getY(best.ids[j])*best.bary.getComponent(j);}result.push(u,v);}mesh.geometry.setAttribute('uv',new THREE.Float32BufferAttribute(result,2));mesh.material=this.materials.head;}
 buildHead(){
  const m=this.materials,skull=new THREE.Group(),upper=muzzle(skull,m.ridge,[[.207,.321,.041,.030],[.250,.330,.074,.041],[.291,.327,.066,.037],[.332,.325,.054,.035],[.390,.316,.040,.028],[.435,.315,.032,.023],[.451,.314,.023,.015]]);this.projectTexture(upper,'jaw_upper');
  for(const s of [-1,1]){
   horn(skull,[[s*.047,.350,.244],[s*.088,.409,.210],[s*.116,.454,.120],[s*.092,.436,.050]],.020,m.horn);
   horn(skull,[[s*.049,.326,.291],[s*.086,.347,.271],[s*.115,.348,.226]],.014,m.ridge);
   horn(skull,[[s*.046,.348,.300],[s*.069,.373,.325],[s*.064,.386,.342]],.012,m.ridge);
   solid(new THREE.SphereGeometry(1,16,10),m.eye,skull,[s*.077,.338,.290],[.011,.004,.011]);
   horn(skull,[[s*.054,.344,.283],[s*.067,.348,.302],[s*.052,.342,.319]],.008,m.ridge);
   solid(new THREE.SphereGeometry(1,12,8),m.mouth,skull,[s*.026,.341,.417],[.008,.003,.010]);
   for(let k=0;k<6;k++){const z=.303+k*.023,y=.299-k*.002,w=.047-k*.002;horn(skull,[[s*w,y,z],[s*(w-.001),y-.008,z+.002],[s*(w-.005),y-(k===3?.024:.013+k%2*.003),z+.009]],.0034,m.tooth);}
   for(let j=0;j<4;j++){const z=.252+j*.033,y=.362-j*.011,x=s*(.034-j*.005);armorLeaf(skull,m.ridge,[x,y,z],.024-j*.002,.029,.006,[.12,0,s*-.26]);}
   armorLeaf(skull,m.ridge,[s*.064,.333,.272],.025,.043,.010,[0,0,s*-1.08]);armorLeaf(skull,m.ridge,[s*.062,.346,.298],.018,.029,.009,[0,-s*.20,s*-.60]);
  }
  for(let j=0;j<4;j++)armorLeaf(skull,m.ridge,[0,.366-j*.010,.260+j*.042],.021-j*.002,.033,.007,[.10,0,0]);
  for(let row=0;row<5;row++)for(const side of [-1,1]){
   const z=.299+row*.025,y=.363-row*.0055;armorLeaf(skull,m.ridge,[side*(.025-row*.002),y,z],.017-row*.001,.020,.004,[.19,side*.22,side*-.30]);
  }
  for(let j=0;j<5;j++)horn(skull,[[0,.344,.240+j*.032],[0,.361,.246+j*.032],[0,.371,.257+j*.030]],.010,m.ridge);skull.scale.set(1.23,1.16,1.64);skull.position.set(0,-.33*.16,-.24*.64);this.mountWorld(skull,'jaw_upper');
  const lower=new THREE.Group(),lowerMesh=muzzle(lower,m.ridge,[[.263,.241,.043,.016],[.310,.239,.052,.019],[.374,.245,.040,.015],[.431,.253,.028,.012]]);this.projectTexture(lowerMesh,'jaw_lower');lowerMesh.material=this.materials.ridge;solid(new THREE.SphereGeometry(1,20,12),m.mouth,lower,[0,.249,.345],[.043,.008,.078]);
  for(const s of [-1,1]){for(let k=0;k<6;k++){const z=.298+k*.019;horn(lower,[[s*.044,.244,z],[s*.043,.254,z+.004],[s*.039,.261,z+.006]],.0035,m.tooth);}horn(lower,[[s*.047,.232,.274],[s*.076,.214,.244],[s*.089,.204,.202]],.012,m.horn);}lower.scale.set(1.21,1.12,1.62);lower.position.set(0,-.25*.12,-.26*.62);this.mountWorld(lower,'jaw_lower');
  this.mouth=new THREE.Object3D();this.mouth.position.set(0,.290,.568);this.root.add(this.mouth);this.root.updateMatrixWorld(true);this.bones.jaw_upper.attach(this.mouth);
 }
 buildClaws(){this.clawTips={};for(const name of ['leg_front_foot_L','leg_front_foot_R','leg_back_foot_L','leg_back_foot_R']){const group=new THREE.Group(),p=this.bones[name].getWorldPosition(V()),front=name.includes('front');for(let i=-1;i<=1;i++){const x=p.x+i*.019,z=p.z+(front?.055:.035);horn(group,[[x,p.y-.010,z],[x+i*.005,p.y-.006,z+.035],[x+i*.006,p.y-.020,z+.057]],.009,this.materials.horn);}const tip=new THREE.Object3D();tip.position.set(p.x,p.y-.020,p.z+(front?.112:.092));group.add(tip);this.clawTips[name]=tip;this.mountWorld(group,name);}}
 buildDorsal(){const m=this.materials;for(const name of ['neck1','neck2','neck3','back1','back2','tail1','tail2','tail3']){const p=this.bones[name].getWorldPosition(V()),g=new THREE.Group(),neck=name.startsWith('neck'),size=neck?.048:name.startsWith('tail')?.044:.080;for(const s of [-1,0,1]){const x=p.x+s*(neck?.034:.051),z=p.z-(neck?.036:0);horn(g,[[x,p.y+.025,z],[x+s*.012,p.y+size,z-.021],[x+s*.021,p.y+size*1.40,z-.054]],size*.25,m.ridge);}this.mountWorld(g,name);}}
 buildArmor(){const m=this.materials;this.ember=new THREE.MeshStandardMaterial({color:0xae250c,emissive:0xb92308,emissiveIntensity:.6,roughness:.6});for(const side of ['L','R']){const s=side==='L'?1:-1;for(const region of ['front','back']){const name='leg_'+region+'_upper_'+side,p=this.bones[name].getWorldPosition(V()),g=new THREE.Group();for(let j=0;j<4;j++)for(let k=0;k<3;k++){const a=(k-1)*.7;armorLeaf(g,m.ridge,[p.x+s*(.025+Math.cos(a)*.021),p.y+.013-j*.024,p.z+Math.sin(a)*.060],.024,.034,.010,[.12,s*-.15,s*(-1.05+a*.20)]);}horn(g,[[p.x+s*.040,p.y+.010,p.z],[p.x+s*.087,p.y+.073,p.z-.025],[p.x+s*.088,p.y+.130,p.z-.093]],.023,m.ridge);horn(g,[[p.x+s*.061,p.y-.010,p.z+.025],[p.x+s*.071,p.y-.035,p.z+.036],[p.x+s*.074,p.y-.050,p.z+.014]],.0018,this.ember);this.mountWorld(g,name);}}
  for(const name of ['neck1','neck2','neck3']){const p=this.bones[name].getWorldPosition(V()),g=new THREE.Group();for(const s of [-1,1]){horn(g,[[s*.046,p.y+.035,p.z-.022],[s*.069,p.y+.056,p.z-.040],[s*.085,p.y+.082,p.z-.076]],.011,m.ridge);horn(g,[[s*.048,p.y+.010,p.z+.018],[s*.049,p.y+.030,p.z+.031],[s*.042,p.y+.050,p.z+.022]],.0012,this.ember);}this.mountWorld(g,name);}
 }
 buildWings(){
  const bones=this.skin.skeleton.bones,skeleton=new THREE.Skeleton(bones,bones.map(b=>b.matrixWorld.clone().invert())),P=[],I=[],SI=[],W=[],UV=[],RP=[],RI=[],RSI=[],RW=[];
  const boneIndex=name=>bones.indexOf(this.bones[name]);
  const weight=(side,u)=>{const upper=Math.max(0,Math.min(1,(u-.13)/.5));return {i:[boneIndex('wing_lower_'+side),boneIndex('wing_upper_'+side),0,0],w:[1-upper,upper,0,0]};};
  for(const [side,s]of [['L',1],['R',-1]]){
   const shoulder=V(s*.068,.052,.018),elbow=V(s*.245,.260,-.028),tips=[V(s*.77,.465,-.015),V(s*.76,.298,-.22),V(s*.64,.132,-.425),V(s*.38,.025,-.48),V(s*.095,.012,-.21)];
   const fingers=tips.map((tip,j)=>new THREE.CatmullRomCurve3([elbow,elbow.clone().lerp(tip,.55).add(V(0,.015,-.015)),tip]));
   for(let panel=0;panel<tips.length-1;panel++){
    const n=12,m=8,offset=P.length/3;
    for(let row=0;row<=n;row++)for(let col=0;col<=m;col++){
     const u=row/n,v=col/m,scallop=1-.23*Math.sin(Math.PI*v)*Math.pow(u,3),radial=u*scallop,pt=fingers[panel].getPoint(radial).lerp(fingers[panel+1].getPoint(radial),v);pt.z+=Math.sin(Math.PI*u)*Math.sin(Math.PI*v)*.026;const sk=weight(side,.4+u*.6);P.push(...pt.toArray());SI.push(...sk.i);W.push(...sk.w);UV.push((panel+v)/(tips.length-1),u);
     if(row<n&&col<m){const a=offset+row*(m+1)+col;I.push(a,a+m+1,a+1,a+1,a+m+1,a+m+2);}
    }
   }
   for(let j=0;j<tips.length;j++){
    const curve=fingers[j],frames=curve.computeFrenetFrames(24,false),off=RP.length/3,k=8;
    for(let t=0;t<=24;t++){const u=t/24,pt=curve.getPoint(u),r=(.008*(1-u)+.0015)*(j===0?1.3:1),sk=weight(side,.4+u*.6);for(let k2=0;k2<k;k2++){const q=pt.clone().addScaledVector(frames.normals[t],Math.cos(k2/k*Math.PI*2)*r).addScaledVector(frames.binormals[t],Math.sin(k2/k*Math.PI*2)*r);RP.push(...q.toArray());RSI.push(...sk.i);RW.push(...sk.w);if(t<24){const a=off+t*k+k2,b=off+t*k+(k2+1)%k;RI.push(a,b,a+k,b,b+k,a+k);}}}
   }
   const curve=new THREE.CatmullRomCurve3([shoulder,shoulder.clone().lerp(elbow,.5).add(V(0,.025,.005)),elbow]),frames=curve.computeFrenetFrames(24,false),off=RP.length/3,k=8;for(let t=0;t<=24;t++){const u=t/24,pt=curve.getPoint(u),sk=weight(side,u*.4),r=.018-u*.005;for(let j=0;j<k;j++){const q=pt.clone().addScaledVector(frames.normals[t],Math.cos(j/k*Math.PI*2)*r).addScaledVector(frames.binormals[t],Math.sin(j/k*Math.PI*2)*r);RP.push(...q.toArray());RSI.push(...sk.i);RW.push(...sk.w);if(t<24){const a=off+t*k+j,b=off+t*k+(j+1)%k;RI.push(a,b,a+k,b,b+k,a+k);}}}
  }
  this.wingMembrane=new THREE.SkinnedMesh(skinGeometry(P,I,SI,W,UV),this.materials.membrane);this.wingRibs=new THREE.SkinnedMesh(skinGeometry(RP,RI,RSI,RW),this.materials.horn);for(const m of [this.wingMembrane,this.wingRibs]){this.root.add(m);m.bind(skeleton,new THREE.Matrix4());m.frustumCulled=false;groundConstrainedWing(m);}
 }
 setEffects(enabled){this.effects=enabled;this.materials.eye.emissiveIntensity=enabled?1.5:0;this.ember.emissiveIntensity=enabled?.6:0;this.materials.hide.emissiveIntensity=enabled?.035:0;this.fissureMaterial.emissiveIntensity=enabled?2.1:0;}
 restoreOverlay(){for(const [bone,q]of this.overlayRestore.reverse())bone.quaternion.copy(q);this.overlayRestore=[];for(const [bone,p]of this.positionRestore||[])bone.position.copy(p);this.positionRestore=[];}
 proportions(){this.positionRestore=[];for(const [name,scale]of [['neck2',1.25],['neck3',1.24],['back2',1.40],['leg_back_hip_L',1.40],['leg_back_hip_R',1.40],['tail1',1.12],['tail2',1.10]]){const bone=this.bones[name];this.positionRestore.push([bone,bone.position.clone()]);bone.position.multiplyScalar(scale);}}
 overlay(bone,axis,amount){if(!bone||!amount)return;this.overlayRestore.push([bone,bone.quaternion.clone()]);bone.rotateOnAxis(axis,amount);}
 posture(name,blend){const factor=blend??(name==='idle'||name==='walk'?1:0);if(!factor)return;const bone=this.bones.neck1;this.root.updateMatrixWorld(true);const axis=V(1,0,0).applyQuaternion(bone.getWorldQuaternion(new THREE.Quaternion()).invert());this.overlay(bone,axis,.49*factor);this.root.updateMatrixWorld(true);const head=this.bones.neck3,headAxis=V(1,0,0).applyQuaternion(head.getWorldQuaternion(new THREE.Quaternion()).invert());this.overlay(head,headAxis,-.23*factor);}
 pose(name,t){this.restoreOverlay();for(const a of Object.values(this.actions))a.stop();const action=this.actions[name]||this.actions.idle;action.reset().play();action.time=Math.max(0,Math.min(t,this.clips[name].duration-.00001));action.paused=true;this.mixer.update(0);this.current=name;this.state=name;this.proportions();this.posture(name);this.ground();}
 ground(){this.body.position.y=0;this.root.updateMatrixWorld(true);this.skin.skeleton.update();let min=Infinity;const geo=this.skin.geometry,ids=geo.index.array,q=V();for(let i=0;i<ids.length;i++){this.skin.getVertexPosition(ids[i],q).applyMatrix4(this.skin.matrixWorld);min=Math.min(min,q.y);}this.body.traverse(m=>{if(!m.isMesh||m.isSkinnedMesh)return;const p=m.geometry.attributes.position;for(let i=0;i<p.count;i+=3){q.fromBufferAttribute(p,i).applyMatrix4(m.matrixWorld);min=Math.min(min,q.y);}});this.body.position.y=-min+.006;this.root.updateMatrixWorld(true);}
 update(actor,t){
  const dt=this.lastT===null?0:Math.max(0,Math.min(.25,t-this.lastT));this.lastT=t;this.restoreOverlay();const yaw=actor.yaw||0;this.yaw=this.yaw===null?yaw:advanceYaw(this.yaw,yaw,dt*.9,!!actor.cast);this.root.rotation.y=this.yaw;
  let name='idle',seek=null;if(actor.state==='dead'){name='die';seek=Math.min(actor.deathTime||0,this.clips.die.duration-.001);}else if(actor.cast){const c=actor.cast,wind=Math.min(1,c.age/c.windup),active=Math.max(0,(c.age-c.windup)/c.life);name='attack';if(c.key==='charge'&&active>0){name='walk';this.actions.walk.timeScale=7.9;}else if(c.key==='charge'){seek=wind*.70;}else if(c.key==='claw'||c.key==='slam'){name='idle';seek=.30;}else if(c.key==='breath'){const elapsed=Math.max(0,c.age-c.windup);seek=active>0?.73+Math.sin(active*Math.PI*4)*.012:wind*.73;}else if(c.key==='summon'){seek=wind*.63+active*.08;}else{seek=wind*1.08+active*(this.clips.attack.duration-1.08);}}else if(actor.moving){name='walk';this.actions.walk.timeScale=(actor.speed||2.05)/1.86;}
  if(this.current!==name){const old=this.actions[this.current],next=this.actions[name];next.reset().play();old.crossFadeTo(next,.18,false);this.current=name;}const action=this.actions[name];if(seek!==null){action.time=seek;action.paused=true}else action.paused=false;this.mixer.update(dt);this.state=name;
  this.proportions();const targetPosture=name==='idle'||name==='walk'?1:0;this.postureBlend??=targetPosture;this.postureBlend+=(targetPosture-this.postureBlend)*(1-Math.exp(-dt*12));this.posture(name,this.postureBlend);this.combatPose(actor);if((actor.hurt||0)>this.lastHurt+.025)this.hurtUntil=t+.38;this.lastHurt=actor.hurt||0;
  if(actor.state!=='dead'&&t<this.hurtUntil){const q=Math.sin(Math.PI*(1-(this.hurtUntil-t)/.38));this.overlay(this.bones.neck1,V(1,0,0),-.20*q);this.overlay(this.bones.neck3,V(0,0,1),.16*q);this.overlay(this.bones.wing_lower_L,V(0,0,1),-.09*q);this.overlay(this.bones.wing_lower_R,V(0,0,1),.09*q);this.state='hurt';}
  this.ground();if(name==='walk')this.plantFeet(actor,dt);else{this.footLocks={};this.lastFootLocal={};}
 }
 // The close-range attack is a foreclaw sweep; a long-neck bite would reach
 // past the shared 4.8-unit warning. Both contact and breath use cast.age.
 combatPose(actor){
  const c=actor.cast;if(!c)return;const wind=THREE.MathUtils.clamp(c.age/c.windup,0,1),after=Math.max(0,c.age-c.windup),smooth=x=>x*x*(3-2*x);
  if(c.key==='breath'){
   const blend=smooth(Math.min(1,wind*1.6))*(1-smooth(THREE.MathUtils.clamp((after-.76)/.34,0,1)));
   this.root.updateMatrixWorld(true);const bone=this.bones.neck3,axis=V(1,0,0).applyQuaternion(this.root.getWorldQuaternion(new THREE.Quaternion())).applyQuaternion(bone.getWorldQuaternion(new THREE.Quaternion()).invert());this.overlay(bone,axis,.34*blend);this.root.updateMatrixWorld(true);const jaw=this.bones.jaw_lower,jawAxis=V(1,0,0).applyQuaternion(this.root.getWorldQuaternion(new THREE.Quaternion())).applyQuaternion(jaw.getWorldQuaternion(new THREE.Quaternion()).invert());this.overlay(jaw,jawAxis,-.28*blend);this.state='attack';
  }
  if(c.key==='claw'||c.key==='slam'){
   const lift=Math.sin(Math.PI*Math.min(1,wind))*.13,settle=1-smooth(Math.min(1,after/.30));
   const sides=c.key==='slam'?['L','R']:[actor.id%2?'L':'R'];
   for(const side of sides){
    this.root.updateMatrixWorld(true);const foot=this.bones['leg_front_foot_'+side],start=this.root.worldToLocal(foot.getWorldPosition(V())),sign=side==='L'?1:-1;
    const reach=smooth(Math.min(1,wind)),target=start.clone();target.x=sign*(.13+.025*Math.sin(wind*Math.PI));target.y=start.y+lift;target.z=start.z+(c.key==='slam'?.045:.13)*reach;
    target.lerp(start,1-settle);this.limbTarget('front',side,this.root.localToWorld(target));
   }
   const q=Math.sin(wind*Math.PI)*.10;this.overlay(this.bones.neck1,V(1,0,0),-q);this.overlay(this.bones.wing_lower_L,V(0,0,1),q*.65);this.overlay(this.bones.wing_lower_R,V(0,0,1),-q*.65);
   this.state='attack';
  }
 }
 limbTarget(region,side,target){
  const upper=this.bones['leg_'+region+'_upper_'+side],lower=this.bones['leg_'+region+'_lower_'+side],foot=this.bones['leg_'+region+'_foot_'+side],A=upper.getWorldPosition(V()),B=lower.getWorldPosition(V()),C=foot.getWorldPosition(V()),ab=B.clone().sub(A),bc=C.clone().sub(B),L1=ab.length(),L2=bc.length(),dir=target.clone().sub(A),d=THREE.MathUtils.clamp(dir.length(),Math.abs(L1-L2)+.001,L1+L2-.001);dir.normalize();target=A.clone().addScaledVector(dir,d);const axis=ab.clone().addScaledVector(dir,-ab.dot(dir)).normalize();if(axis.lengthSq()<.2)return;
  for(const bone of [upper,lower,foot])this.overlayRestore.push([bone,bone.quaternion.clone()]);const footQ=foot.getWorldQuaternion(new THREE.Quaternion()),x=(d*d+L1*L1-L2*L2)/(2*d),h=Math.sqrt(Math.max(0,L1*L1-x*x)),newB=A.clone().addScaledVector(dir,x).addScaledVector(axis,h),q=new THREE.Quaternion().setFromUnitVectors(ab.normalize(),newB.clone().sub(A).normalize()).multiply(upper.getWorldQuaternion(new THREE.Quaternion()));upper.quaternion.copy(upper.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(q));upper.updateWorldMatrix(false,true);const actualB=lower.getWorldPosition(V()),actualC=foot.getWorldPosition(V()),lq=new THREE.Quaternion().setFromUnitVectors(actualC.sub(actualB).normalize(),target.clone().sub(actualB).normalize()).multiply(lower.getWorldQuaternion(new THREE.Quaternion()));lower.quaternion.copy(lower.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(lq));lower.updateWorldMatrix(false,true);foot.quaternion.copy(foot.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(footQ));this.root.updateMatrixWorld(true);
 }
 plantFeet(actor,dt){const offset=V((actor.x||0)/15,0,(actor.z||0)/15);for(const region of ['front','back'])for(const side of ['L','R']){const key=region+'_'+side,upper=this.bones['leg_'+region+'_upper_'+side],lower=this.bones['leg_'+region+'_lower_'+side],foot=this.bones['leg_'+region+'_foot_'+side],end=foot.getWorldPosition(V()),local=this.root.worldToLocal(end.clone()),previous=this.lastFootLocal[key];this.lastFootLocal[key]=local;const returning=previous&&dt>0&&(local.z-previous.z)/dt>.025,contact=end.y<(region==='front'?.049:.039)&&!returning;if(!contact){delete this.footLocks[key];continue;}let lock=this.footLocks[key];if(!lock)this.footLocks[key]=lock=end.clone().add(offset);const target=lock.clone().sub(offset),shift=target.clone().sub(end),A=upper.getWorldPosition(V()),B=lower.getWorldPosition(V()),ab=B.clone().sub(A),bc=end.clone().sub(B),L1=ab.length(),L2=bc.length(),dir=target.clone().sub(A),d=dir.length();if(shift.length()>.075||d>=L1+L2-.0002||d<=Math.abs(L1-L2)+.0002){this.footLocks[key]=end.clone().add(offset);continue;}dir.normalize();const axis=ab.clone().addScaledVector(dir,-ab.dot(dir)).normalize();if(axis.lengthSq()<.2){delete this.footLocks[key];continue;}for(const b of [upper,lower,foot])this.overlayRestore.push([b,b.quaternion.clone()]);const footQ=foot.getWorldQuaternion(new THREE.Quaternion()),x=(d*d+L1*L1-L2*L2)/(2*d),h=Math.sqrt(Math.max(0,L1*L1-x*x)),newB=A.clone().addScaledVector(dir,x).addScaledVector(axis,h),q=new THREE.Quaternion().setFromUnitVectors(ab.normalize(),newB.clone().sub(A).normalize()).multiply(upper.getWorldQuaternion(new THREE.Quaternion()));upper.quaternion.copy(upper.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(q));upper.updateWorldMatrix(false,true);const actualB=lower.getWorldPosition(V()),actualC=foot.getWorldPosition(V()),lq=new THREE.Quaternion().setFromUnitVectors(actualC.sub(actualB).normalize(),target.clone().sub(actualB).normalize()).multiply(lower.getWorldQuaternion(new THREE.Quaternion()));lower.quaternion.copy(lower.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(lq));lower.updateWorldMatrix(false,true);foot.quaternion.copy(foot.parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(footQ));this.root.updateMatrixWorld(true);}}
 metrics(){return {state:this.state,bones:Object.keys(this.bones).length,scales:this.scaleCount,detail:this.detail,scaleDrawCalls:1,baseTriangles:this.skin.geometry.index.count/3,scaleTriangles:this.scaleMesh.geometry.index.count/3,wingTriangles:(this.wingMembrane.geometry.index.count+this.wingRibs.geometry.index.count)/3};}
}
export class DragonRenderer{
 constructor({resolution=768}={}){this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});this.renderer.setSize(resolution,resolution);this.renderer.setClearColor(0,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.scene=new THREE.Scene();const pm=new THREE.PMREMGenerator(this.renderer);this.scene.environment=pm.fromScene(new RoomEnvironment(),.05).texture;pm.dispose();this.scene.environmentIntensity=.7;this.scene.add(new THREE.HemisphereLight(0xc9d4e8,0x321009,1.8));const key=new THREE.DirectionalLight(0xffd9bd,3);key.position.set(-2,4,3);this.scene.add(key);const rim=new THREE.DirectionalLight(0x7894bd,2);rim.position.set(2,2,-3);this.scene.add(rim);this.camera=new THREE.OrthographicCamera(-1.12,1.12,1.12,-1.12,.01,20);this.camera.position.set(3,5.35,4);this.camera.lookAt(0,.35,0);}
 setCharacter(dragon){if(this.char)this.scene.remove(this.char.root);this.char=dragon;this.scene.add(dragon.root);}
 render(){this.renderer.render(this.scene,this.camera);const origin=V().project(this.camera);return {canvas:this.renderer.domElement,x:(origin.x+1)/2,y:(1-origin.y)/2,span:2.24};}
 draw(ctx,actor,x,y,unit,t){this.char.update(actor,t);const mouth=this.char.mouth.getWorldPosition(V());actor.mouthWorld={x:actor.x+mouth.x*15,y:mouth.y*15,z:actor.z+mouth.z*15};const r=this.render(),size=unit*15*r.span;ctx.drawImage(r.canvas,x-r.x*size,y-r.y*size,size,size);}
}
export async function createDragonBridge(){const gltf=await loadDragon(),quality=new URLSearchParams(location.search).get('bossQuality'),detail=['high','balanced','low'].includes(quality)?quality:innerWidth<=960?'balanced':'high',renderer=new DragonRenderer({resolution:detail==='high'?768:512}),instances=new Map();return {gltf,renderer,instances,detail,ready:true,draw(ctx,actor,x,y,unit,t){let dragon=instances.get(actor.id);if(!dragon){dragon=new R10Dragon(gltf,{detail});instances.set(actor.id,dragon)}renderer.setCharacter(dragon);renderer.draw(ctx,actor,x,y,unit,t);for(const [id,c]of instances)if(id!==actor.id&&instances.size>8)instances.delete(id);}};}
