(function(root){
// Nine verified original GIF identities only. Placements are project design.
const selections=[['gludio_wilderness',['skeleton',6]],['kent_vineyard',['elder',4]],['silver_knight_forest',['orc',4],['wolf',4],['spider',4]],['windawood_desert',['scorpion',4]],['orc_forest',['orc',6]],['elven_forest'],['giran_bandits',['banditLeader',4]],['heine_swamp',['crabman',4]],['heine_mirror',['darkElf',4]],['dragon_valley',['skeleton',6]],['fire_valley']];
const species={skeleton:{name:'骷髏',file:30,hp:260,height:4.2},orc:{name:'獸人',file:56,hp:240,height:3.8},wolf:{name:'狼',file:96,hp:180,height:3},spider:{name:'巨蛛',file:1082,hp:220,height:2.5},elder:{name:'長者',file:32,hp:220,height:4.3,ranged:true,projectileKind:'magic'},scorpion:{name:'毒蠍',file:4060,hp:240,height:3.6,archetype:'spider'},banditLeader:{name:'強盜隊長',file:2417,hp:320,height:4.3},crabman:{name:'蟹人',file:1610,hp:260,height:3.5},darkElf:{name:'黑暗妖精',file:1125,hp:260,height:4.5,ranged:true,projectileKind:'arrow'}};let groups=[];
function load(data){groups=data;}
function create({spawn,blocked,rng,hero}){const catalogue=[],populations=[],configuration=[];
 for(const [regionId,...entries] of selections){const group=groups.find(x=>x.id===regionId);configuration.push({regionId,names:entries.map(([kind])=>species[kind].name),visuals:entries.map(([kind])=>kind),count:entries.reduce((n,e)=>n+e[1],0),placement:'project-design',assets:'nine original GIF species',friendlyRest:regionId==='elven_forest',restProvenance:regionId==='elven_forest'?'prototype arrangement; no hostile NPC substitutes':null,unimplemented:(group?.recommended?.names||[]).filter(name=>!entries.some(([kind])=>species[kind].name===name)),boss:regionId==='fire_valley'?'ifrit':regionId==='windawood_desert'?'antQueen':null});
  for(const [kind,count] of entries){const s=species[kind],id=regionId+'-'+kind;catalogue.push({id,name_zh:s.name,role:{value:s.ranged?'ranged':'melee'},kind});populations.push({regionId,count,pool:[id]});}
 }
 const byId=new Map(catalogue.map(x=>[x.id,x]));const spawner=R11Regions.createSpawner({catalogue,populations,rng,blocked:(x,z,r)=>blocked(x,z,r)||(Math.abs(x)<24&&z>46&&z<91),respawnSeconds:20,isAlive:m=>m.state!=='dead',spawn:request=>{const entry=byId.get(request.catalogueId),kind=entry.kind,s=species[kind],level=R11Regions.regions.find(r=>r.id===request.regionId).level,hp=s.hp+level*8;return spawn(s.archetype||(['wolf','spider','skeleton'].includes(kind)?kind:'skeleton'),request.x,request.z,{name:s.name,regionId:request.regionId,catalogueId:entry.id,visualKind:kind,originalGif:s.file,hp,maxHp:hp,dmg:kind==='wolf'?9:12,speed:kind==='wolf'?2.8:2.3,reach:s.ranged?7:kind==='spider'?1.8:2.05,ranged:!!s.ranged,projectileKind:s.projectileKind,projectileHeight:s.ranged?2.7:undefined,labelHeight:s.height+.3,xp:28+level*5});}});spawner.step(0,hero);return {spawner,configuration};
}root.R12World={load,create,selections,species};})(globalThis);
